---
title: True Drama
author: Macmillan Films
tagline: "A Macmillan Films Production"
baseurl: ""
url: https://truedramamovie.com
email: james@macmillanfilms.com
enforce_ssl: truedramamovie.com
description: |
  Strange Bacchic disturbances in the woods protesting a local horror
  movie prompt a police investigation. A shadowy figure emerges. Calling himself the
  God of Drama, he believes that he can achieve the seemingly impossible goal of returning
  drama to its original purpose – of preparing citizens for leadership in democracy.
image: "/assets/img/logo.svg"
collections:
  actors:
    title: Actors
    output: true
    permalink: "/:collection/:title"
    source: actors.csv
    layout: actor
    id_key: id
defaults:
  - scope:
      path: ""
      type: actors
    values:
      layout: actor
      banner: "/assets/img/hero.jpg"
  - scope:
      path: ""
    values:
      youtube: fz2SIyeKMIg
      g01: "/assets/img/gallery/true-drama-01.jpg"
      g01dsc: offering handcuffs modeling a new kind of policing
      g01alt: Tatiana Galliher
      g02: "/assets/img/gallery/true-drama-02.jpg"
      g02dsc: jumping fire in a secret ritual
      g02alt: Morgan Marcum
      g03: "/assets/img/gallery/true-drama-03.jpg"
      g03dsc: attempts escape from the Slashers nest
      g03alt: Alanah Rafferty
      g04: "/assets/img/gallery/true-drama-04.jpg"
      g04dsc: center stage in True Drama
      g04alt: James Thomas
      g05: "/assets/img/gallery/true-drama-05.jpg"
      g05dsc: deep underground in the private mausoleum
      g05alt: Tatiana Galliher
      g06: "/assets/img/gallery/true-drama-06.jpg"
      g06dsc: Driving up to the Greenwich mansion modeled after the Château de Malmaison in French
      g06alt: Tatiana Galliher
      g07: "/assets/img/gallery/true-drama-07.jpg"
      g07dsc: Officer Walsh approached the wealth Greenwich patron Mrs. Benedict
      g07alt: Tatiana Galliher
      g08: "/assets/img/gallery/true-drama-08.jpg"
      g08dsc: a close-up of the new terrifying slasher mask with it's fish-like gaping mouth
      g08alt: AYohan Belmin
      g09: "/assets/img/gallery/true-drama-09.jpg"
      g09dsc: showing the climactic Exodus of the drama
      g09alt: James Thomas
      g10: "/assets/img/gallery/true-drama-10.jpg"
      g10dsc: Officer Walsh finds Dionysus in the rafters of the theater at the abandoned sanitarium
      g10alt: Tatiana Galliher
      g11: "/assets/img/gallery/true-drama-11.jpg"
      g11dsc: Dionysus looks down from the rigging of the theater at the abandoned sanitarium
      g11alt: James Thomas
      g12: "/assets/img/gallery/true-drama-12.jpg"
      g12dsc: Sara's POV from inside a coffin, looking up at the terrifying masked slasher
      g12alt: Scott Kozel
      g13: "/assets/img/gallery/true-drama-13.jpg"
      g13dsc: A tracking shot of the slasher taking his female captive to his underground lair
      g13alt: Scott Kozel
      g14: "/assets/img/gallery/true-drama-14.jpg"
      g14dsc: Mr. B directs from the control room as Sara is chained to a rack before being tortured
      g14alt: Aidan Laliberte
      g15: "/assets/img/gallery/true-drama-15.jpg"
      g15dsc: Sara begs through her prison bars of the slasher's lair
      g15alt: Alanah Rafferty
      g16: "/assets/img/gallery/true-drama-16.jpg"
      g16dsc: Detective Oliva and Officer Walsh drive to meet the writer of the slasher script
      g16alt: Jose Ramos
      g17: "/assets/img/gallery/true-drama-17.jpg"
      g17dsc: Officer Walsh sees posters for Greek Dramas in the foyer of the theater at the abandoned sanitarium
      g17alt: Tatiana Galliher
      g18: "/assets/img/gallery/true-drama-18.jpg"
      g18dsc: Officer Walsh hears something unnerving she approached the theater stage
      g18alt: Tatiana Galliher
      g19: "/assets/img/gallery/true-drama-19.jpg"
      g19dsc: Dionsysos uses flash powder to create a distraction so he can avoid being tased by police
      g19alt: James Thomas
      g20: "/assets/img/gallery/true-drama-20.jpg"
      g20dsc: Sara feels someone is looking at her through the window, as she showers in the Slasher's house
      g20alt: Alanah Rafferty
      g21: "/assets/img/gallery/true-drama-21.jpg"
      g21dsc: The Greenwich Slasher wearing his mask and spying on the women in the shower
      g21alt: Yohan Belmin
      g22: "/assets/img/gallery/true-drama-22.jpg"
      g22dsc: Miss Ukraine and the other female victims try to stay save amid the chaos on set
      g22alt: Katka Krajcovic
      g23: "/assets/img/gallery/true-drama-23.jpg"
      g23dsc: Detective Oliva in from of the crime board
      g23alt: Jose Ramos
      g24: "/assets/img/gallery/true-drama-24.jpg"
      g24dsc: Driving up to the Greenwich mansion modeled after the Château de Malmaison in French
      g24alt: Jose Ramos
      g01thumb: "/assets/img/gallery/thumb/true-drama-01.jpg"
      g02thumb: "/assets/img/gallery/thumb/true-drama-02.jpg"
      g03thumb: "/assets/img/gallery/thumb/true-drama-03.jpg"
      g04thumb: "/assets/img/gallery/thumb/true-drama-04.jpg"
      g05thumb: "/assets/img/gallery/thumb/true-drama-05.jpg"
      g06thumb: "/assets/img/gallery/thumb/true-drama-06.jpg"
      g07thumb: "/assets/img/gallery/thumb/true-drama-07.jpg"
      g08thumb: "/assets/img/gallery/thumb/true-drama-08.jpg"
      g09thumb: "/assets/img/gallery/thumb/true-drama-09.jpg"
      g10thumb: "/assets/img/gallery/thumb/true-drama-10.jpg"
      g11thumb: "/assets/img/gallery/thumb/true-drama-11.jpg"
      g12thumb: "/assets/img/gallery/thumb/true-drama-12.jpg"
      g13thumb: "/assets/img/gallery/thumb/true-drama-13.jpg"
      g14thumb: "/assets/img/gallery/thumb/true-drama-14.jpg"
      g15thumb: "/assets/img/gallery/thumb/true-drama-15.jpg"
      g16thumb: "/assets/img/gallery/thumb/true-drama-16.jpg"
      g17thumb: "/assets/img/gallery/thumb/true-drama-17.jpg"
      g18thumb: "/assets/img/gallery/thumb/true-drama-18.jpg"
      g19thumb: "/assets/img/gallery/thumb/true-drama-19.jpg"
      g20thumb: "/assets/img/gallery/thumb/true-drama-20.jpg"
      g21thumb: "/assets/img/gallery/thumb/true-drama-21.jpg"
      g22thumb: "/assets/img/gallery/thumb/true-drama-22.jpg"
      g23thumb: "/assets/img/gallery/thumb/true-drama-23.jpg"
      g24thumb: "/assets/img/gallery/thumb/true-drama-24.jpg"
timezone: America/New_York
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
compress_html:
  clippings: all
  startings: all
  endings: all
  comments:
    - - "<!-- , -->"
    - - "/* , */"
sass:
  style: compressed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
